### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [leamerluck/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out - hint: including a link to the commit where you added the code is what web developers usually do  :)

**Comment by leamerluck** [comment]
So, I added the mobile meta tag (viewpoint - device width). Here is my commit: https://github.com/leamerluck/splurty/blob/master/app/views/layouts/application.html.erb

**Comment by MarcoMorawec** [comment]
@leamerluck :+1: and nice job!

Looks like [this commit](https://github.com/leamerluck/splurty/commit/17caeceda54d54aa02a4416c0c709f311b8abfb1) did the trick :)

Make sure you close the issue, now that you solved it.
